# Generated by Django 2.0.2 on 2018-02-16 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courseProviderID', models.CharField(max_length=50)),
                ('courseName', models.CharField(max_length=200)),
                ('authorName', models.CharField(max_length=200)),
                ('courseUrl', models.URLField(max_length=500)),
                ('courseSummary', models.TextField()),
                ('courseCategory', models.CharField(max_length=200)),
                ('isDownloaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('providerName', models.CharField(max_length=200)),
                ('providerUrl', models.URLField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='providerID',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.SET_DEFAULT, to='getvid.Provider'),
        ),
    ]
