# Generated by Django 2.0.2 on 2018-02-16 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('getvid', '0002_auto_20180216_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='providerID',
            field=models.ForeignKey(default=uuid.UUID('6fa459ea-ee8a-3ca4-894e-db77e160355e'), on_delete=django.db.models.deletion.SET_DEFAULT, to='getvid.Provider'),
        ),
    ]
